l_polish:
 SETTINGS_PAGE_GRAPHICS: "Grafika"
 SETTINGS_PAGE_GAME: "Hra"
 SETTINGS_PAGE_SYSTEM: "Systém"
 SETTINGS_PAGE_CONTROLS: "Ovládanie"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Rozhranie"
 SETTINGS_PAGE_AUDIO: "Zvuk"
 SETTINGS_CATEGORY_SCREEN: "Obrazovka"
 SETTINGS_CATEGORY_QUALITY: "Kvalita"
 OPTION_EASY: "Ľahká"
 OPTION_NORMAL: "Normálna"
 OPTION_HARD: "Ťažká"
 OPTION_NEVER: "Nikdy"
 OPTION_MONTHLY: "Každý mesiac"
 OPTION_HALFYEAR: "Každého pol roka"
 OPTION_YEARLY: "Každý rok"
 OPTION_FIVE_YEAR: "Každých päť rokov"
 OPTION_NO_AUTOSAVE: "Nevykonávať automatické ukladanie"
 SETTINGS_CATEGORY_ACCOUNT: "Účet"
 SETTINGS_CATEGORY_SYSTEM: "Systém"
 SETTINGS_CATEGORY_CONTROLS: "Ovládanie"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_AUDIO: "Zvuk"
 SETTINGS_CATEGORY_GUI: "Rozhranie"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Mapovanie"
 DISCARD: "Zrušiť"
 APPLY: "Použiť"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Nastavenia"
 REQUIRES_RESTART: "Vyžaduje reštart"
 REQUIRE_RESTART_DESCRIPTION: "Niektoré nastavenia sa prejavia až po reštarte hry."
 DISABLED_BECAUSE_IS_SET: "Deaktivované, pretože „$SETTING_NAME$“ je nastavené na „$SETTING_VALUE$“"
 SETTINGS_INPUT_REMAP_INPUT: "Zmeniť ovládanie"
 SETTINGS_INPUT_CONFIRM: "Potvrdiť"
 SETTINGS_INPUT_CANCEL: "Zrušiť"
 SETTINGS_INPUT_CLEAR: "Vymazať"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Uložiť profil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Načítať profil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Obnoviť predvolené"
 SETTINGS_INPUT_BINDING_TEXT: "Vyberte klávesovú alebo ovládaciu väzbu pre akciu „$INPUT_ACTION$“:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Upozornenie: Táto väzba už existuje pre „$INPUT_ACTION$“!\nStlačením „$SETTINGS_INPUT_CONFIRM$“ sa stará väzba odstráni."
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Upozornenie: väzba nemôže pozostávať iba z modifikačných klávesov"
 SETTINGS_PAGE_ACCOUNT: "Účet"
 SETTING_TELEMETRY_CONSENT: "Odosielať dobrovoľné telemetrické údaje"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Súhlas s telemetriou\n#!Umožňuje odosielať dobrovoľné telemetrické údaje spoločnosti Paradox Interactive."
