l_polish:
  SETTING_REFRACTION: "Refrakcia"
  SETTING_REFRACTION_QUALITY: "Kvalita refrakcie"
  SETTING_MAPOBJECT_QUALITY: "Objekty na mape"
  SETTING_MAP_SSAO: "Mapa – SSAO"
  SETTING_DOF: "Hĺbka ostrosti"
  SETTING_LENS_FLARE: "Odlesk objektívu"
  SETTING_SECONDARY_LENS_FLARE: "Sekundárny odlesk objektívu"
