l_polish:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Mierka nad $VALUE|%0$ spôsobí, že rozhranie sa nezmestí na obrazovku#!"
 RECOMMENDED_GUI_SCALE: "Mierka nad $VALUE|%0$ spôsobí, že rozhranie sa nezmestí na obrazovku"
