l_polish:
 # Všeobecné
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ sekúnd"
 SETTING_VALUE_MINUTES: "$VALUE$ minút"

 # Grafika
 SETTING_RENDERER: "Renderer"
 SETTING_RENDERER_TOOLTIP: "Určuje, ktorý renderer sa používa."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Synchronizuje snímkovú frekvenciu hry s monitorom, čím sa znižuje trhanie obrazu.\n\nVypnutie môže zvýšiť výkon."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Viacnásobné vzorkovanie portrétov"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Používa viacnásobné vzorkovanie Alpha-To-Coverage pre plynulejšie prechody vlasov.\n\nNižšie nastavenie zvyšuje výkon."
 SETTING_MULTI_SAMPLING: "Vyhladzovanie hrán (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Viacnásobné vzorkovanie MSAA zjemní okraje objektov.\n\nNižšie nastavenia môžu zvýšiť výkon."
 SETTING_ANTI_ALIASING: "Vyhladzovanie hrán"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Vyhladzovanie hrán robí okraje objektov plynulejšie.\n\nOdporúča sa FXAA."
 OPTION_ANTI_ALIASING_DISABLED: "Vypnuté"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"

 SETTING_UPSCALE: "Metóda upscalingu"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nMetódy upscalingu umožňujú dosiahnuť vyššie rozlíšenie prostredníctvom algoritmického prevzorkovania. Môže to zvýšiť výkon, ale aj spôsobiť vizuálne artefakty.\n\nDostupné metódy závisia od vašej grafickej karty."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"

 SETTING_UPSCALE_QUALITY: "Kvalita upscalingu"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nUrčuje, či sa má upscaling zamerať na kvalitu alebo výkon."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra kvalita"
 OPTION_UPSCALE_QUALITY_QUALITY: "Kvalita"
 OPTION_UPSCALE_QUALITY_BALANCED: "Vyvážené"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Výkon"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Maximálny výkon"

 SETTING_ANISOTROPIC_FILTERING: "Filtrovanie textúr"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Anizotropné filtrovanie zlepšuje vzhľad textúr.\n\nNižšie nastavenia môžu zvýšiť výkon."
 SETTING_RESOLUTION: "Rozlíšenie"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Určuje kvalitu obrazu hry.\n\nNižšie rozlíšenia môžu zvýšiť výkon.\n\n#X Rozlíšenia s nepodporovaným pomerom strán môžu spôsobiť, že rozhranie sa nezmestí na obrazovku#!"
 SETTING_RENDER_SCALE: "Mierka vykresľovania"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nMierka vykresľovacieho rozlíšenia hry voči hlavnému rozlíšeniu (bez rozhrania).\n\nNižšie nastavenia znižujú kvalitu, ale zvyšujú výkon."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"

 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Ak máte viac monitorov, vyberte, na ktorom sa hra zobrazí."
 SETTING_GRAPHICS_DEVICE: "Grafická karta"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Určuje, ktorú grafickú kartu hra použije.\n\nPoužívanie integrovanej grafiky môže znížiť výkon."
 SETTING_SHADOW_MAP_RESOLUTION: "Kvalita tieňov"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Určuje rozlíšenie tieňových máp, ak sú tiene zapnuté.\n\nNižšie nastavenia môžu zvýšiť výkon."
 SETTING_DISPLAY_MODE: "Režim zobrazenia"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Určuje, ako sa hra zobrazí na obrazovke."

 SETTING_BLOOM_QUALITY: "Bloom efekt"
 SETTING_MESH_LOD_BIAS: "Kvalita LOD modelov"
 SETTING_MESH_LOD_FADE: "Prechod LOD modelov"
 SETTING_TERRAIN_SMOOTHING: "Vyhladzovanie terénu"

 OPTION_FULLSCREEN: "Celá obrazovka"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Zobrazí hru na celej obrazovke. Rozlíšenie ovplyvňuje ostrosť obrazu."
 OPTION_WINDOWED: "Okno"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Zobrazí hru v okne. Rozlíšenie mení veľkosť okna."

 OPTION_DISABLED: "Vypnuté"
 OPTION_OFF: "Vypnuté"
 OPTION_LOW: "Nízka"
 OPTION_MEDIUM: "Stredná"
 OPTION_HIGH: "Vysoká"
 OPTION_VERY_HIGH: "Veľmi vysoká"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Vlastné"
 OPTION_DEFAULT: "Predvolené"

 SETTINGS_CATEGORY_UI: "Rozhranie"
 SETTINGS_CATEGORY_GAME: "Hra"

 SETTING_TEXTURE_QUALITY: "Kvalita textúr"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nUrčuje rozlíšenie načítaných textúr.\n\nNižšie nastavenia môžu zvýšiť výkon."

 SETTING_QUALITY: "Predvoľba kvality"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Vyberte predvoľbu grafických nastavení nižšie.\n\nNižšia kvalita zvyšuje výkon."
 SETTING_SFX: "Efekty"
 SETTING_UI: "Rozhranie"

 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Aktivuje „bloom“ efekt, ktorý spôsobí, že jasné svetlá presvitajú do iných častí obrazu.\n\nVypnutie môže zvýšiť výkon."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Simuluje hĺbku ostrosti ako pri kamere, rozmazáva neostré časti obrazu.\n\nVypnutie môže zvýšiť výkon."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Aktivuje odlesky šošoviek v silne osvetlených oblastiach.\n\nBloom musí byť zapnutý."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Aktivuje sekundárne odlesky šošoviek. Bloom musí byť zapnutý.\n\nVypnutie môže zvýšiť výkon."

 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Určuje, či sa na mapu použije ambientná oklúzia (SSAO).\n\nVypnutie môže zvýšiť výkon."
 SETTING_REFRACTION_TOOLTIP: "Určuje, či sa na vode zobrazujú lomy svetla."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nUrčuje kvalitu lomov svetla na vode.\n\nNižšie nastavenia môžu zvýšiť výkon."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nUrčuje kvalitu objektov na mape (napr. budov).\n\nNižšie nastavenia môžu zvýšiť výkon."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nUrčuje kvalitu LOD (úrovne detailov) modelov jednotiek.\n\nNižšie nastavenia môžu zvýšiť výkon."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Ak je zapnuté, modely sa pri približovaní plynule menia medzi úrovňami detailu.\n\nVypnutie môže zvýšiť výkon."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Určuje, ako sa zobrazujú názvy miest a provincií na mape."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Určuje, či sa nepriechodný terén zobrazuje v rámci hraníc krajiny."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nUrčuje jazyk používateľského rozhrania."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "E-mail vášho Paradox účtu."
 SETTING_FRAMERATE_CAP: "Maximálny počet FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nMaximálny počet snímok za sekundu, ktoré hra vykreslí.\n\nNižšie nastavenia môžu znížiť spotrebu energie."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"

 SETTING_TEXTURE_STREAMING: "Streamovanie textúr"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTextúry sa načítavajú podľa potreby.\n\nZnižuje využitie pamäte GPU, no mierne zaťažuje procesor."
 SETTING_TEXTURE_STREAMING_CACHE: "Veľkosť vyrovnávacej pamäte textúr"
 SETTING_VALUE_MB: "$VALUE$ MB"

 # GUI
 SETTING_ANIMATION_SPEED: "Rýchlosť animácií"
 SETTING_GUI_SCALING: "Mierka rozhrania"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Určuje veľkosť používateľského rozhrania, vhodné pre vysoké rozlíšenia.\n\n#X Príliš vysoké nastavenie môže spôsobiť, že sa rozhranie nezmestí na obrazovku!#!"
 SETTING_TOOLS_GUI_SCALING: "Mierka rozhrania nástrojov"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Určuje veľkosť rozhrania editorov a nástrojov.\n\n#X Príliš vysoké nastavenie môže spôsobiť, že sa rozhranie nezmestí na obrazovku!#!"

 # Systém
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Posun myšou pri okraji"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Voľný"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 smerov"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Vypnuté"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nUrčuje, ako sa kamera správa pri posúvaní myšou."
 SETTING_SCROLL_SPEED: "Rýchlosť posunu"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nUrčuje, ako rýchlo sa mapa posúva pomocou myši alebo klávesnice."
 SETTING_CAMERA_ROTATION_SPEED: "Rýchlosť otáčania kamery"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nUrčuje, ako rýchlo sa kamera otáča."
 SETTING_ZOOM_SPEED: "Rýchlosť priblíženia"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nUrčuje, ako rýchlo sa kamera približuje a odďaľuje."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Správanie priblíženia"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Relatívne ku kurzoru"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Priblížiť ku kurzoru"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignorovať kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nUrčuje, ako sa kamera správa pri približovaní myšou."
 SETTING_INPUT_DEVICE: "Vstupné zariadenie"
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_POSTFIX: "Editor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Príkaz na otvorenie editora"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Príkaz na zobrazenie logu"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Príkaz na otvorenie kódu"
 SETTING_GRACEFUL_EXIT: "Bezpečné ukončenie"
 SETTING_LANGUAGE: "Jazyk"
 MOUSE_AND_KEYBOARD: "Myš a klávesnica"
 GAMEPAD: "Gamepad"

 # Editor
 SETTING_CAMERA_TILT: "Náklon kamery"
 SETTING_CAMERA_STRATEGY: "Typ kamery"
 SETTING_CENTERED_ZOOM_IN: "Centrované priblíženie"
 SETTING_CAMERA_SPEED: "Rýchlosť kamery"
 CAMERA_TABLETOP: "Pohľad zhora"
 CAMERA_FPS: "Prvá osoba"
 CAMERA_WASD: "Štýl WASD"

 # Zvuk
 SETTING_Music: "Hudba"
 SETTING_Ambient: "Prostredie"
 SETTING_Effects: "Efekty"
 SETTING_Master: "Hlavná hlasitosť"
 SETTING_VO: "Hlasový prejav"
 SETTING_VO_TOOLTIP: "#T Hlasový prejav\n#!Určuje hlasitosť dabingu v hre."
 SETTING_Master_TOOLTIP: "#T Hlavná hlasitosť\n#!Určuje celkovú hlasitosť hry."
 SETTING_Music_TOOLTIP: "#T Hudba\n#!Určuje hlasitosť hudby."
 SETTING_Ambient_TOOLTIP: "#T Prostredie\n#!Určuje hlasitosť zvukov prostredia."
 SETTING_SFX_TOOLTIP: "#T Zvukové efekty\n#!Určuje hlasitosť zvukových efektov ako boj či interakcie."
 SETTING_UI_TOOLTIP: "#T Rozhranie\n#!Určuje hlasitosť zvukov používateľského rozhrania."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Úroveň logovania zvuku"
 SETTING_AUDIO_DEVICE_PROFILE: "Zvukový profil"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Vyberte zvukový profil podľa svojho zariadenia."
 SETTING_AUDIO_OPTION_SPEAKERS: "Reproduktory"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Predvolený mix pre reproduktory."
 SETTING_AUDIO_OPTION_HEADPHONES: "Slúchadlá"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix prispôsobený pre slúchadlá."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix určený pre TV a vstavané reproduktory monitorov."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Nočný režim"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Zjemňuje zvuky pre hranie v noci, znižuje vysoké tóny a vyrovnáva hlasitosť."
 SETTING_MUSIC_DENSITY: "Hustota hudby"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Určuje pomer medzi pesničkami, tichom a atmosférickými segmentmi.\n\nIntenzívne = väčšinou jedna skladba za druhou.\nVyvážené = rovnováha medzi hudbou, tichom a atmosférou.\nUvoľnené = viac pokojných segmentov pre dlhé hranie."

 # Hra
 SETTING_AUTOSAVE: "Interval automatického ukladania"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Určuje, ako často sa hra automaticky uloží."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Určuje, či sa automatické uloženia ukladajú do cloudu."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Určuje, či kamera bude vždy smerovať na sever."
 NO_AUTOSAVE: "Bez automatického ukladania"
 SETTING_ENABLE_PARTICLES: "Častice"
 SETTING_ENABLE_PARTICLES_TOOLTIP: "#T $SETTING_ENABLE_PARTICLES$\n#!Zapína alebo vypína časticové efekty v hre."

 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Rýchlosť prenosu súborov"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $SETTINGS_FILE_TRANSFER_SPEED$#!\nUrčuje maximálnu rýchlosť prenosu uložených hier v multiplayeri.\n\nNižšie hodnoty môžu zlepšiť stabilitu siete, ale spomalia načítanie."

 # Nástroje
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Automatické uloženie mapového editora (minúty)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Interval automatického uloženia v editore máp (v minútach)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Režim ťahania v editore uzlov"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Režim automatického dopĺňania konzoly"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Úplné rozšírenie (cyklus cez tab)"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Čiastočné rozšírenie do rozdielu"

 # Prístupnosť
 SETTINGS_CATEGORY_ACCESSIBILITY: "Prístupnosť"
 SETTING_COLOR_BLIND_MODE: "Režim pre farboslepých"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Mení farby použité v texte v celej hre na takú sadu farieb, ktorá sa ľahšie rozlišuje pre rôzne typy farbosleposti."
